### ISSUE TITLE
languageCode for "zh-cn" don't show Chinese

### ISSUE THREAD

**Issue by sunkehappy** [cntrump/hugo-notepadium#107]
Hugo Version:  v0.74.3
Build Command: hugo server

I have already set the `languageCode = "zh-cn"` in `config.toml` but my page still the English "Categories" instead of the "分类" in `zh.toml`. Is there something wrong?

**Comment by ClSlaid** [comment]
try "zh" instead

**Comment by cntrump** [comment]
W3C 标准里的简体中文是 `zh-Hans`，但 Hugo 不支持，改成了 `zh`。
`zh-CN` 是兼容旧的写法，好像现在不推荐了？

**Comment by sunkehappy** [comment]
@cntrump 我试了`languageCode = "zh"`，这样也不行，还是显示的英文，有别的可能的原因吗？

**Comment by cntrump** [comment]
> @cntrump 我试了`languageCode = "zh"`，这样也不行，还是显示的英文，有别的可能的原因吗？

设置 `defaultContentLanguage` 才是网页语言，`languageCode` 是给 RSS 用的。

```toml
languageCode = "zh"  # for the RSS generation
defaultContentLanguage = "zh"
```
