### ISSUE TITLE
[HOW TO] Using web fonts

### ISSUE THREAD

**Issue by cntrump** [cntrump/hugo-notepadium#16]
1. Choose a font from [Google Fonts](https://fonts.google.com/)

    - example `Open Sans`
    - download the CSS `curl -O https://fonts.googleapis.com/css?family=Open+Sans&display=swap`
    - copy content of CSS file.

2. Create a `fonts.css` at yout site root: `./assets/css/fonts.css`
    
    Paste the css code from step 1

    And Override the `font-family`

    ```css
    [CSS CODE FROM STEP 1]

    html {
        font-family: 'Averia Sans Libre', -system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Helvetica, SimHei, 'Segoe UI', Roboto, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
    }
    ```

3. Edit `config.toml`

    ```toml
    [params.assets]
    css = ["css/fonts.css"]
    ````

4. Done, run `hugo server` take a look.
