### ISSUE TITLE
How to use DarkMode Theme

### ISSUE THREAD

**Issue by dannykorpan** [cntrump/hugo-notepadium#2]
Hi,

how is it possible to use the DarkMode Theme?

Thanks!

Kind Regards

**Comment by cntrump** [comment]
dark mode is automatically enabled, based on system settings.

**Comment by cntrump** [comment]
Or remove `@media (prefers-color-scheme: dark)` from `style.css`.

**Comment by cntrump** [comment]
fetch latest code and update your `config.toml`

```toml
[params]
style = "dark"
```

It means use dark mode always.

- **Light** mode
    ```toml
    [params]
    style = "light"
    ```
- **Dark** mode
    ```toml
    [params]
    style = "dark"
    ```

- **Auto**, based on system.
    ```toml
    [params]
    style = "auto"
    ```
