### ISSUE TITLE
[HOW TO] Custom Style simply

### ISSUE THREAD

**Issue by cntrump** [cntrump/hugo-notepadium#21]
1. Add `light.css`, `dark.css` to your `./assets/css/`
2. Edit `config.toml`, add CSS path
    ```toml
    [params.assets]
    css = ["css/light.css", "css/dark.css"]
    ```

    Note, `dark.css` MUST at last.

Example of `light.css` & `dark.css`

`light.css`

```css
body { background-color: #f4f7ef; }

.base-body {
    background-color: #fff;
    padding: 8px 0;
    border-radius: 8px;
    box-shadow: rgba(0, 0, 0, .15) 0 10px 30px;
}
```

`dark.css`
```css
@media (prefers-color-scheme: dark) {

body { background-color: #222; }

.base-body {
    color: #fff;
    background-color: #24292e;
    padding: 8px 0;
    border-radius: 8px;
    box-shadow: rgba(220, 220, 220, .15) 0 10px 30px;
}

}
```

Preview: https://notepadiumstyle.lvv.me/shadow/
