### ISSUE TITLE
[HOW TO] Modeled Medium's layout style

### ISSUE THREAD

**Issue by cntrump** [cntrump/hugo-notepadium#23]
`config.toml`

```toml
[params.assets]
css = ["css/layout.css"]
```

`layout.css`

```css
.note.list .item > .note,
.article.markdown-body pre,
.article.markdown-body .image-container {
  margin-left: -20px;
  margin-right: -20px;
}

.note.list .item > .note,
.article.markdown-body pre {
  padding-left: 20px;
  padding-right: 20px;
}

.article.markdown-body pre,
.article.markdown-body .image-container .img {
  border: 0;
  border-radius: 0;
}

@media (max-width: 375px) {
  .note.list .item > .note,
  .article.markdown-body pre,
  .article.markdown-body .image-container {
    margin-left: -15px;
    margin-right: -15px;
  }

  .note.list .item > .note,
  .article.markdown-body pre {
    padding-left: 15px;
    padding-right: 15px;
  }
}
```
