### ISSUE TITLE
Does this need to be !important?

### ISSUE THREAD

**Issue by Benjamin-Lee** [cntrump/hugo-notepadium#25]
https://github.com/cntrump/hugo-notepadium/blob/cc96f7408e0699fc776c33211c2e91c45b33adfb/assets/css/style.css#L633

**Comment by cntrump** [comment]
It will be overrided by

```css
.article.markdown-body> :last-child,
.article.markdown-body li> :last-child,
.article.markdown-body blockquote> :last-child {
  margin-bottom: 0 !important;
}
```

Or we should remove these all `!important` ?

```css
.article.markdown-body li+li {
  margin-top: 20px !important;
}

.article.markdown-body>*,
.article.markdown-body li>*,
.article.markdown-body blockquote>* {
  margin-top: 0 !important;
  margin-bottom: 20px !important;
}

.article.markdown-body> :first-child,
.article.markdown-body li> :first-child,
.article.markdown-body blockquote> :first-child {
  margin-top: 0 !important;
}

.article.markdown-body> :last-child,
.article.markdown-body li> :last-child,
.article.markdown-body blockquote> :last-child {
  margin-bottom: 0 !important;
}
```
