### ISSUE TITLE
Multilingual support?

### ISSUE THREAD

**Issue by gatto** [cntrump/hugo-notepadium#27]
Hi! This is my fave Hugo theme. Would it be hard to add multi language support out of the box?

**Comment by cntrump** [comment]
https://gohugo.io/content-management/multilingual/

set IsMultiLingual = true on config.toml:

```toml
isMultiLingual = true
```

and  https://gohugo.io/content-management/multilingual/#translation-by-content-directory

I think you should fork and make some changes:

replace `relURL` with `relLangURL`

**Comment by gatto** [comment]
Thank you for the answer. I'm a complete Hugo noob. I'll try and if I manage to do anything useful I'll fork and pull request.

But for the content management, I'd much rather use https://gohugo.io/content-management/multilingual/#translation-by-filename

**Comment by cntrump** [comment]
I think I figure it out, update latest code please.

and, edit your `config.toml`, add :

```toml
isMultiLingual = true
defaultContentLanguage = "zh"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
  [languages.zh]
    contentDir = "content/zh"
    languageName = "Chinese"
    weight = 20
```

Try it...
