### ISSUE TITLE
[HOW TO] update DarkMode like as moonlight style

### ISSUE THREAD

**Issue by cntrump** [cntrump/hugo-notepadium#30]
a nice vscode theme: https://github.com/atomiks/moonlight-vscode-theme

```css
@media (prefers-color-scheme: dark) {
  body {
    background-color: #222436;
  }
  
  body,
  .site.name,
  .note.title,
  .note.content,
  .article.markdown-body,
  .image-container .title {
    color: #c8d3f5;
  }
  
  mark {
    background-color: #3c4361;
  }
  
  .site.slogan .title,
  .note.date,
  .article.date,
  .footer {
    color: #828bb8;
  }
  
  code,
  kbd,
  tt,
  samp {
    color: #f7a4ec;
  }
  
  a {
    color: #82aaff;
  }
  
  .pagination ul li a {
    color: #82aaff;
  }
  
  .pagination ul li a.active {
    background-color: #82aaff;
  }
  
  .pagination ul li a:hover:not(.active) {
    background-color: rgba(130, 170, 255, .5);
  }
  
  .tag {
    color: #fc7b7b;
  }
  
  .category {
    color: #ffc777;
  }
  
  .note.list .item a:hover,
  .nav.item:hover,
  .article.tag:hover,
  .article.category:hover {
    background-color: #3c4361;
  }
  
  /* border color */
  pre,
  .note.imgs .img,
  .image-container .img,
  .article.markdown-body table td,
  .article.markdown-body table th,
  .article.markdown-body .lntable {
    border-color: rgba(116, 198, 241, 0.15);
  }
  
  .article.markdown-body h1,
  .article.markdown-body h2,
  .image-container .title,
  .site.slogan .title,
  .note.list .item {
    border-bottom-color: rgba(116, 198, 241, 0.15);
  }
  
  .article.discussion {
    border-top-color: rgba(116, 198, 241, 0.15);
    border-bottom-color: rgba(116, 198, 241, 0.15);
  }
  
  .article.markdown-body .lntable tr>:first-child {
    border-right-color: rgba(116, 198, 241, 0.15);
  }
}
```
