### ISSUE TITLE
Q: Doesn't show up built-in header items 'Categories' and 'Tags'

### ISSUE THREAD

**Issue by jinnyjinnyjinjin-zz** [cntrump/hugo-notepadium#40]
Hugo Version:  v0.60.1

I can't see the 'Categories' and 'Tags' right side of header after running server. I've checked documentation and mentions though.
I haven't modified 'showCategories' and 'showTags'. I just let them 'true' values.

**Comment by cntrump** [comment]
try cd exampleSite and run `hugo --themesDir ../.. server`
 'Categories' and 'Tags' ok?

**Comment by jinnyjinnyjinjin-zz** [comment]
I've already tried it. 
I couldn't see them either.

**Comment by cntrump** [comment]
Chrome? Firefox? or IE?
and OS version

**Comment by jinnyjinnyjinjin-zz** [comment]
Mac os Catalina and chrome.

**Comment by cntrump** [comment]
Same macos and chrome as you.
But this problem can't be reproduced for me, no any idea now...

**Comment by foresukecom** [comment]
I had the same issue.

When I wrote `defaultContentLanguage =" ja-JP "` in config.toml, 'Categories' and 'Tags' were not displayed.
However, when I wrote `defaultContentLanguage =" en "`, it was displayed.

Hugo: v0.63.2

**Comment by cntrump** [comment]
> I had the same issue.
> 
> When I wrote `defaultContentLanguage =" ja-JP "` in config.toml, 'Categories' and 'Tags' were not displayed.
> However, when I wrote `defaultContentLanguage =" en "`, it was displayed.
> 
> Hugo: v0.63.2

Thanks, helpful for me!
I think it is a hugo's feature... https://github.com/gohugoio/hugo/issues/2451

**Comment by jinnyjinnyjinjin-zz** [comment]
I've figured what was the my problem. 
It didn't work even when I've executed the original code without any modification.
The problem was Version of hugo.  My version was v1.60.1 the latest is v0.64.1 until now.
I upgraded hugo and it works.

Also, I have same issue like @foresukecom has. 
It's still in issue as @cntrump mentioned but you can temporary fix and use.

Create `ja.toml` file to `<your-hugo-project-name>/themes/<your-theme-name>/i18n/` and copy below content to the file.  

```toml
[edited]
other = " • edited %s"

[readingTime]
one = " • One minute to read"
other = " • {{ .Count }} minutes to read"

[more]
other = "more"

[Categories]
other = "Categories"

[Tags]
other = "Tags"
```
after this, change the value of variables which are in `config.toml` file like below.
```toml
languageCode = "ja"
defaultContentLanguage = "ja"
```
and run hugo server again. 
Then you will see the menu. It worked for me.
