### ISSUE TITLE
Extra space between mathjax output

### ISSUE THREAD

**Issue by Alanthink** [cntrump/hugo-notepadium#72]
Hugo Version:  0.60.0

Thanks for providing such a nice theme.

I am trying to use MathJax instead of Katex for math display. However, there is extra space around MathJax output. See the example below.

![image](https://user-images.githubusercontent.com/17557588/79919835-204b6d00-83fd-11ea-82ee-4483a7407410.png)

Do you have any idea why this happens?

**Comment by Alanthink** [comment]
It seems to me that in the `style.css`, you added padding around MathJax output. Do you think it is a good idea to remove that? Like the following. @cntrump 

```css
.article.markdown-body .katex,
.article.markdown-body .MathJax,
.article.markdown-body .katex-display,
.article.markdown-body .MathJax_Display {
  margin: 0;
  padding: 0em 0em;
}
```

**Comment by cntrump** [comment]
I updated style.css, just remove `padding`:

```css
.article.markdown-body .katex,
.article.markdown-body .MathJax {
  margin: 0;
  padding: 0;
}
```
