### ISSUE TITLE
Mailto link in navbar doesn't work

### ISSUE THREAD

**Issue by Benjamin-Lee** [cntrump/hugo-notepadium#8]
I want to have a link in the navbar to allow someone to contact me. For example, in config.yaml:

```yaml
  nav:
    showCategories: true
    showTags: true
    custom:
      - title: About
        url: /about
      - title: GitHub
        url: https://github.com/Benjamin-Lee
      - title: Email
        url: mailto:benjamindlee@me.com
```

The rendered HTML is linking to `/mailto:benjamindlee@me.com` rather than `mailto:benjamindlee@me.com`, which yields a 404.
