### ISSUE TITLE
Icon font does not work

### ISSUE THREAD

**Issue by reitzig** [cntrump/hugo-notepadium#91]
The included icon font does not render for me (FF 75.0, Ubuntu 18.04 LTS). The font file loads okay. Other web fonts render fine.

[My own page](https://reitzig.github.io/today-i-learned/posts/2020-04-24-navigating-slack/):

![image](https://user-images.githubusercontent.com/4246780/83518484-c7cabd80-a4da-11ea-8ab0-a4a9ac51b0a2.png)

[Demo](https://themes.gohugo.io//theme/hugo-notepadium/post/math-typesetting/#examples):

![image](https://user-images.githubusercontent.com/4246780/83518739-1d06cf00-a4db-11ea-8ecd-ef9029340666.png)

Note the navigation links at the bottom, showing ![image](https://user-images.githubusercontent.com/4246780/83518848-458ec900-a4db-11ea-857a-ce0f8a4aaef3.png) instead of a symbol.

Screenshots taken with urlbox.io to exclude my local setup as a cause. Same result with url2png.com.

**Comment by cntrump** [comment]
I updated iconfont. could u help me test it ?

**Comment by reitzig** [comment]
Sure thing!

(Would test releases help with such things? That, or branches/PRs? I think I'd prefer linking my submodule to a tag or branch instead of pulling `master` or linking individual references. :thinking: )

**Comment by reitzig** [comment]
I don't see any font file being loaded, despite there now being multiple ones. :thinking: 

![image](https://user-images.githubusercontent.com/4246780/83747570-1b671380-a661-11ea-928f-a308b4a31800.png)

**Comment by cntrump** [comment]
> I don't see any font file being loaded, despite there now being multiple ones. 🤔

iconfont data embed in CSS (base64 encode)

**Comment by reitzig** [comment]
Ah, I see. :heavy_check_mark: 

Anyway, doesn't seem to work. Once thing I note:

```css
@font-face {font-family: "iconfont";
  src: url('{{- $fontDir -}}/iconfont.eot?t=1591245391370'); /* IE9 */
  src: url('{{- $fontDir -}}/iconfont.eot?t=1591245391370#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('data:application/x-font-woff2;charset=utf-8;base64,d09GMgABAAAAAAVIAAsAAAAAClgAAAT6AAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHEIGVgCDbAqHAIVpATYCJAMgCxIABCAFhG0HchvlCCOSD06S7B+JsbHyw8yHSpV4ty2SETnY2DYZqc7kQ3jWv8lMsMkaanoCunftt7oHsvvp4sR8AEmAADi/b87aHqA7YUadC8raI49+4e9ykjeZ0tGl6U0KhQJWJ3UtIFEstVlv1iyAEQxFS/1SKnfAfwB8lH+It7rMs4EAkBGJdJD6z/Z+SGDQVxEAZFacOh5SwgNWwSaQ7ELBniyaPAUeEvcw9wGAJ73fJ98gl0gAB55C39g9pWESqu/HfHmGmnSTUQ4F7XAhAOx+AAWQDoAB5KHCyDo0yKWDQpZvx6AC8IQEDsL9GE3WZmlLtbtfntF1kgozu/UIgadB944A4qCSHBh4CH88AWhxB+Ykl4ij1FoERECTCVBAm0mAANosAhygLSXAAO0uAR748owVB0yXlnsDCASgQ2YRZr6NGOs5CJB9fDLqBerNdHOYfYVfFw57acuZt9NGWgdCR+x96/TmkKkvmUKG73nz3Lbk5pHWrWffSF5pvzfuEafqcBmdjutEEW4mZxrOOsm2LIfD4HR1fezoIR2DQ8Vvtw21P1/zGv2Oy4YdLxLV7gw6eNF/766AExfwqiPJeiio3ffZ5Ep7wZn3gsPw/qMtLpf/Ebv/Hgfs9v7nD6Df9HKS66rRqc2eMHPRhJXLqGG55869RBzYl+S1Yw8E026V92RjFcjwgLtlGhl1LpSJQmUoBoApYLzX7J3OfKeamrzfnvHcG7K33WFwKK67xhMuY9aKcjXAiA3zxt4r0ebbgpg+9kjyEXsCC7LN16BYYr57JZX/BErWqbiaMydWVrdlNWX0uW1Kr82rJ9M6A6r//LbVa9Q8tHNv+1zIHlngdqhn4o15awXPxuI1v/z4cKBfo8e94//QL146eM0D0XThZRYdzS5z+2z0lfxYXaFO9WrsSEythvOdasNK2mjE6iJyZjj/6FT6hFto/cMjxMYErk5qzvzE/Akq/bfnEsTG1uVh9an0yUenDOevdMbjUeXHXGu+jXL72OXoaOhre//7bGBYeOK1ajKUzQDbWhR0p+31ftAXvg9602Vl/XvVvQak9qkMk2q5dDseE+d2mpeaY83Lzdbd5iXmIsGy3GJdFn/W5M7ZvdISqam56EjaWXHRR29HxE5270g7VNwwd/3Vb9H1Se+bubPCEmpIzVMtrVzWxVg5uNiyxDIodJyNlQAA/TwFZR6LM3N1hrbAI7BouYOaaJr+h27jCa3+QS+Gns0NpWO9yn+TFAYAuPK/tQtUzcAUMQF/mRWNtb+ji0cFpRsUve6VmDTYUnfwoKEi9ZAhxwGQo67fMOGLG0NaAybUOCYpoWWRg4gIpJAQD4yZjjwU5KMACVUoIw1N+yvwwwJQEOYGIBUWggTeOIQcPGFDCm98CIx5HXkE4jsU4E0oymj87+WIT15JfHxjKIElfaFo5smZfnn0m7/hD0VxXO9x/sFrTNLQ9uniFybwEFvWox9FHDmeK32S86GUmRaeE4y0QWTZd50reqXWzHXz6A0DRYBF0C4IkTGbOGe0eMz8/DfwDgqFK/rK8v+AreL4hAEt+gbwZZka9V3K9NWRN0IIRy1z2KwifEIIipGbEZbieQkYokXokFns0eEw19TSTm+rd9qGmzhAP6YURyhhhCcCEYlE3HC/8gcfPsuTv3lhHCNOd3KKIuBb704LB31dVSzPis9vx4KmxAm3djYZvNkAAAA=') format('woff2'),
  url('{{- $fontDir -}}/iconfont.woff?t=1591245391370') format('woff'),
  url('{{- $fontDir -}}/iconfont.ttf?t=1591245391370') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+ */
  url('{{- $fontDir -}}/iconfont.svg?t=1591245391370#iconfont') format('svg'); /* iOS 4.1- */
}
```
I understand the comma-list as "dear browser, pick the first that works" -- but why is the IE9 one separate? Doesn't this create a conflict?

Anyway, neither creating a single `src` attribute nor simplifying all the way to

```css
@font-face {font-family: "iconfont";
  src:  url('{{- $fontDir -}}/iconfont.ttf?t=1591245391370') format('truetype');
}
```

makes it work for me (even though `iconfont.ttf` resolves with 200). :/ :thinking: 

Out of curiosity, what did you select here (fontello.com)?

![image](https://user-images.githubusercontent.com/4246780/83749606-3dae6080-a664-11ea-8ad1-32bd6931c8c7.png)
